system: "base16"
name: "Default"
author: "aztui"
variant: "dark"
palette:
  base00: "1e293b"
  base01: "4B5563"
  base02: "334155"
  base03: "94A3B8"
  base04: "94A3B8"
  base05: "E5E7EB"
  base06: "F8FAFC"
  base07: "F8FAFC"
  base08: "F87171"
  base09: "F59E0B"
  base0A: "F59E0B"
  base0B: "22C55E"
  base0C: "38BDF8"
  base0D: "60A5FA"
  base0E: "C084FC"
  base0F: "94A3B8"
